import './globals.css'
// import { Inter } from 'next/font/google'
import { Open_Sans } from '@next/font/google'
import Link from 'next/link'
import styles from './rootStyle.module.css'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const openSans = Open_Sans({
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <head />
      <body>
        <header>
        <h1>
          <Link
            className={styles.homeLink}
            href="/home">Globomantics</Link>
        </h1>
        <h2>
          <Link
            className={styles.menuLink}
            href="/blog">blog</Link>
        </h2>
        <h2>
          <Link
            className={styles.menuLink}
            href="/conference">Settings</Link>
        </h2>
        <h2>
          <Link
            className={styles.menuLink}
            href="/conference">Conference</Link>
        </h2>
        </header>
        <section>
        {children}
        </section>
        
      </body>
    </html>
  )
}
